[package]
org = "tharmigan"
name = "ballerina_passthrough"
version = "0.1.0"
distribution = "2201.12.8"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.14.6"
repository = "local"
